"""initial_full_sync

Revision ID: 333bd39b70fd
Revises: 
Create Date: 2025-12-21 23:33:20.123872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '333bd39b70fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_explanations', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('ai_explanations', 'entity_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('budgets', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('budgets', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('budgets', 'category_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.drop_constraint('budgets_user_id_category_id_key', 'budgets', type_='unique')
    op.create_unique_constraint('uq_user_budget_cat', 'budgets', ['user_id', 'category_id'])
    op.alter_column('categories', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('categories', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('categories', 'parent_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.drop_constraint('categories_user_id_name_key', 'categories', type_='unique')
    op.drop_index('idx_categories_parent', table_name='categories')
    op.create_unique_constraint('uq_user_category', 'categories', ['user_id', 'name'])
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('financial_goals', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('financial_goals', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('goal_allocations', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('goal_allocations', 'goal_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('goal_allocations', 'income_source_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('goal_allocations', 'portfolio_holding_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('goal_conflicts', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('goal_conflicts', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('income_sources', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('income_sources', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('income_sources', 'source_type',
               existing_type=postgresql.ENUM('salary', 'business', 'rental', 'dividend', 'interest', 'other', name='income_type_enum'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('income_sources', 'rate_type',
               existing_type=postgresql.ENUM('fixed', 'market_linked', 'api_driven', name='rate_type_enum'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'fixed'::rate_type_enum"))
    op.alter_column('merchant_category_map', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('merchant_category_map', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('merchant_category_map', 'merchant_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('merchant_category_map', 'category_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.drop_constraint('merchant_category_map_user_id_merchant_id_key', 'merchant_category_map', type_='unique')
    op.create_unique_constraint('uq_user_merchant_map', 'merchant_category_map', ['user_id', 'merchant_id'])
    op.alter_column('merchant_master', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('merchant_master', 'canonical_name_norm',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('merchant_master', 'default_category_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('merchant_master', 'aliases',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.drop_index('idx_merchant_norm_trgm', table_name='merchant_master', postgresql_ops={'canonical_name_norm': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('portfolio_holdings', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('portfolio_holdings', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('portfolio_holdings', 'asset_type',
               existing_type=postgresql.ENUM('stock', 'crypto', 'bond', 'mutual_fund', 'gold', 'real_estate', name='asset_type_enum'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('raw_financial_events', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('raw_financial_events', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.drop_index('idx_raw_events_pending', table_name='raw_financial_events', postgresql_where='(parsed = false)')
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('transactions', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('transactions', 'merchant_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('transactions', 'category_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('transactions', 'source',
               existing_type=postgresql.ENUM('manual', 'voice', 'chatbot', 'csv', 'notification', 'wallet', 'blockchain', name='txn_source_enum'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transactions', 'raw_event_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.drop_index('idx_txn_user_date', table_name='transactions')
    op.alter_column('user_wallets', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('user_wallets', 'user_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.drop_constraint('user_wallets_user_id_address_key', 'user_wallets', type_='unique')
    op.create_unique_constraint('uq_user_wallet', 'user_wallets', ['user_id', 'address'])
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('wallet_transactions', 'id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('wallet_transactions', 'wallet_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.alter_column('wallet_transactions', 'category_id',
               existing_type=sa.UUID(),
               type_=app.models.all_models.GUIDType(length=36),
               existing_nullable=True)
    op.drop_constraint('wallet_transactions_chain_tx_hash_key', 'wallet_transactions', type_='unique')
    op.create_unique_constraint('uq_chain_hash', 'wallet_transactions', ['chain', 'tx_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chain_hash', 'wallet_transactions', type_='unique')
    op.create_unique_constraint('wallet_transactions_chain_tx_hash_key', 'wallet_transactions', ['chain', 'tx_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('wallet_transactions', 'category_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('wallet_transactions', 'wallet_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('wallet_transactions', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('users', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_constraint('uq_user_wallet', 'user_wallets', type_='unique')
    op.create_unique_constraint('user_wallets_user_id_address_key', 'user_wallets', ['user_id', 'address'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_wallets', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('user_wallets', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_index('idx_txn_user_date', 'transactions', ['user_id', sa.text('occurred_at DESC')], unique=False)
    op.alter_column('transactions', 'raw_event_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('transactions', 'source',
               existing_type=sa.String(),
               type_=postgresql.ENUM('manual', 'voice', 'chatbot', 'csv', 'notification', 'wallet', 'blockchain', name='txn_source_enum'),
               existing_nullable=False)
    op.alter_column('transactions', 'category_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('transactions', 'merchant_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('transactions', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('transactions', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_index('idx_raw_events_pending', 'raw_financial_events', ['parsed'], unique=False, postgresql_where='(parsed = false)')
    op.alter_column('raw_financial_events', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('raw_financial_events', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('portfolio_holdings', 'asset_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('stock', 'crypto', 'bond', 'mutual_fund', 'gold', 'real_estate', name='asset_type_enum'),
               existing_nullable=True)
    op.alter_column('portfolio_holdings', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('portfolio_holdings', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_index('idx_merchant_norm_trgm', 'merchant_master', ['canonical_name_norm'], unique=False, postgresql_ops={'canonical_name_norm': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('merchant_master', 'aliases',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('merchant_master', 'default_category_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('merchant_master', 'canonical_name_norm',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('merchant_master', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_constraint('uq_user_merchant_map', 'merchant_category_map', type_='unique')
    op.create_unique_constraint('merchant_category_map_user_id_merchant_id_key', 'merchant_category_map', ['user_id', 'merchant_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('merchant_category_map', 'category_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('merchant_category_map', 'merchant_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('merchant_category_map', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('merchant_category_map', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('income_sources', 'rate_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('fixed', 'market_linked', 'api_driven', name='rate_type_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'fixed'::rate_type_enum"))
    op.alter_column('income_sources', 'source_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('salary', 'business', 'rental', 'dividend', 'interest', 'other', name='income_type_enum'),
               existing_nullable=True)
    op.alter_column('income_sources', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('income_sources', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('goal_conflicts', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('goal_conflicts', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('goal_allocations', 'portfolio_holding_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('goal_allocations', 'income_source_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('goal_allocations', 'goal_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('goal_allocations', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('financial_goals', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('financial_goals', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('chat_sessions', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('chat_messages', 'session_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('chat_messages', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_constraint('uq_user_category', 'categories', type_='unique')
    op.create_index('idx_categories_parent', 'categories', ['parent_id'], unique=False)
    op.create_unique_constraint('categories_user_id_name_key', 'categories', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'parent_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('categories', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('categories', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_constraint('uq_user_budget_cat', 'budgets', type_='unique')
    op.create_unique_constraint('budgets_user_id_category_id_key', 'budgets', ['user_id', 'category_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('budgets', 'category_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('budgets', 'user_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('budgets', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('ai_explanations', 'entity_id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('ai_explanations', 'id',
               existing_type=app.models.all_models.GUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
